### ISSUE TITLE
Chess: Move C4 to C4

### ISSUE THREAD

**Issue by amariwan** [marcizhu/marcizhu#1147]
Please do not change the title. Just click "Submit new issue". You don't need to do anything else :D

**Comment by marcizhu** [comment]
@amariwan your README chess at [amariwan/amariwan](https://github.com/amariwan/amariwan) it's not properly set up and redirects to _my_ README chess at [marcizhu/marcizhu](https://github.com/marcizhu/marcizhu). Please fix it. I have instructions on how to set it up properly at [marcizhu/readme-chess](https://github.com/marcizhu/readme-chess).

Also, "Move C4 to C4" is invalid and the bot crashed. I will fix it soon so that it doesn't crash even with invalid inputs, though.

Finally, it would be nice if you could leave the text on the bottom that links back to the original repo so more people can discover it. Thanks.
