### ISSUE TITLE
aaaaa"; ls -la; dir #

### ISSUE THREAD

**Issue by g4mm4** [marcizhu/marcizhu#637]

**Comment by marcizhu** [comment]
@g4mm4 as far as I know this repo is immune to this sort of RCE. First of all, the GitHub Action is only executed if the issue starts with `Chess: `. Second (and most important), I don't directly feed the issue title to the script, but rather I feed it the issue number (so `637` in this case) through an environment variable. The script then uses that number and the repository name to retrieve the issue title, which will always be treated as a string.

Thank you for opening this issue, it made me reconsider the security of this repo :)

**Comment by marcizhu** [comment]
@g4mm4 I would also like to point out that publicly disclosing vulnerabilities and attack vectors on other people's repositories is never a good idea to say the least. Indeed my code was vulnerable to RCE and luckily I managed to patch it before anyone else discovered this. But if someone, looking at your attempt just tried to go one step further and managed to get and RCE working, they could have deleted **EVERYTHING** in this repository. Or even worse: someone could have leaked the `GITHUB_TOKEN` and published/accessed private repos or any other personal information available through my profile. You had no right to do this publicly. If you wanted to have fun or find bugs/vulnerabilities, you could have created a private repo from [my README chess template](https://github.com/marcizhu/readme-chess), experiment for a while and after you find an RCE vulnerability email me so I could fix it PRIVATELY, not publicly.

I hope you reconsider your current behavior and stop trying to show the world which repos are vulnerable and how to exploit that. Once again, you have NO RIGHT to expose people to this level of danger. This is not a game. People's projects, privacy and personal data is on the line. You want to do this? Fine. Fork a repo, make it private, play with it and if you find something, then email the maintainers so they can fix things and assess the danger instead of having to rush things because some idiot decided to do all of this publicly and now anyone can do whatever they want on that repo.

It's because of people like you that [security policies](https://docs.github.com/es/code-security/getting-started/adding-a-security-policy-to-your-repository) are even a thing. Because people like you think that publicly disclosing critical vulnerabilities is a good idea and don't even consider doing research on private and then letting the maintainers know what's wrong with their code. It is never a good idea and I hope you reconsider your current actions.

**Comment by g4mm4** [comment]
Hi Marc,
Sorry for any inconvenience :). The payload is submitted automatically by
my bot
Congratz on your successful fix
cheers,
~g4mm4

**Comment by marcizhu** [comment]
In that case I would consider disabling such a bot for the reasons stated above. This is not something that should be automated and mass-tested on publicly-available repositories.
